### ISSUE TITLE
OSX support?

### ISSUE THREAD

**Issue by andig** [tsufeki/react-filesystem-monitor#2]
Maybe fswatch- which can be installed via homebrew- can be used: https://stackoverflow.com/questions/1515730/is-there-a-command-like-watch-or-inotifywait-on-the-mac

**Comment by tsufeki** [comment]
Hi, my rough try is here #3 - feel free to try it out and comment.

There is no `start` event (fired after watchers are set up) cause I haven't figured a way to get this from fswatch.

**Comment by andig** [comment]
> There is no start event (fired after watchers are set up) cause I haven't figured a way to get this from fswatch.

I haven't either (unless you use `-v` which creates too much noise). Just emit manually then once process has successfully started?
