### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by andig** [tsufeki/react-filesystem-monitor#4]
Might be implemented together with #3 (though I have no need) since according to `man fswatch` it supports:

    A monitor based on the ReadDirectoryChangesW Microsoft Windows API.

**Comment by tsufeki** [comment]
Unlikely to happen as react/child-process [does not support windows](https://github.com/reactphp/child-process#windows-compatibility).

**Comment by andig** [comment]
Yikes- good point :/
